# Generated by Django 2.1 on 2018-08-18 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beer_mart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beer',
            old_name='owner',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='owner',
            new_name='user',
        ),
    ]
