# Generated by Django 2.1 on 2018-08-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer_mart', '0002_auto_20180818_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='ibu',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='beer',
            name='abv',
            field=models.FloatField(),
        ),
    ]
